name: shopify-location-consolidation
services:
- name: api
  source_dir: /
  github:
    repo: your-username/shopify-location-consolidation
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: SHOPIFY_SHOP_DOMAIN
    value: ${SHOPIFY_SHOP_DOMAIN}
    type: SECRET
  - key: SHOPIFY_ACCESS_TOKEN
    value: ${SHOPIFY_ACCESS_TOKEN}
    type: SECRET
  - key: SHOPIFY_API_KEY
    value: ${SHOPIFY_API_KEY}
    type: SECRET
  - key: SHOPIFY_API_SECRET
    value: ${SHOPIFY_API_SECRET}
    type: SECRET
  - key: USA_LOCATION_ID
    value: ${USA_LOCATION_ID}
    type: SECRET
  - key: WEBHOOK_SECRET
    value: ${WEBHOOK_SECRET}
    type: SECRET 