name: Scheduled Order Check

on:
  schedule:
    # Run every hour except between 10:00 UTC and 21:00 UTC
    - cron: '0 0-9 * * *'  # Run at minute 0 of hours 0-9 UTC
    - cron: '0 22-23 * * *'  # Run at minute 0 of hours 22-23 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  check-new-orders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Cache processed orders
      uses: actions/cache@v3
      id: processed-orders-cache
      with:
        path: scripts/processed-orders.json
        key: processed-orders-${{ runner.os }}
        restore-keys: |
          processed-orders-${{ runner.os }}
        
    - name: Process unfulfilled orders
      env:
        SHOPIFY_SHOP_DOMAIN: ${{ secrets.SHOPIFY_SHOP_DOMAIN }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        USA_LOCATION_ID: ${{ secrets.USA_LOCATION_ID }}
      run: |
        node scripts/process-single-order.js

    - name: Upload processed orders cache
      uses: actions/cache@v3
      if: steps.processed-orders-cache.outputs.cache-hit != 'true'
      with:
        path: scripts/processed-orders.json
        key: processed-orders-${{ runner.os }}
        restore-keys: |
          processed-orders-${{ runner.os }} 